version: "3.8"

services:
  frontend:
    build:
      context: ./HRFB/roaster
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://backend:5011

  backend:
    build:
      context: ./roasrserver
    ports:
      - "5011:5011"
